services:
  postgres:
    image: postgres:17-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5401:5432"
volumes:
  postgres_data:
