# Generated by Django 5.0.3 on 2024-10-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseapp', '0002_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
