# Generated by Django 5.0.3 on 2024-10-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseapp', '0003_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file',
            new_name='files',
        ),
    ]
