# Generated by Django 5.0.3 on 2024-10-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseapp', '0004_rename_file_uploadedfile_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='files',
            new_name='file',
        ),
    ]
